# NLP Exercises

We have five exercises in this section. The exercises are:
1. Build your own tokenizer, where you need to implement two functions to implement a tokenizer based on regular expression.
2. Get tags from Trump speech.
3. Get the nouns in the last 10 sentences from Trump's speech and find the nouns divided by sentencens. Use SpaCy.
4. Build your own Bag Of Words implementation using tokenizer created before.
5. Build a 5-gram model and clean up the results.

## Exercise 1. Build your own tokenizer

Build two different tokenizers:
- ``tokenize_sentence``: function tokenizing text into sentences,
- ``tokenize_word``: function tokenizing text into words.

https://note.nkmk.me/en/python-split-rsplit-splitlines-re/#:~:text=If%20you%20want%20to%20split,()%20of%20the%20re%20module.&text=In%20re.,consecutive%20numbers%20is%20as%20follows.

https://regexusingpython.wordpress.com/2019/04/02/regex-module-lets-begin/

https://www.geeksforgeeks.org/regular-expression-python-examples-set-1/

In [123]:
from typing import List
import re


def tokenize_words(text: str) -> list:
    pattern = "\w+" #this works pretty well, although it is not perfect.
    words = re.findall(pattern, text)


    return words

def tokenize_sentence(text: str) -> list:
    
    pattern = '[^.=\?\!]+.=\?\!|[^.=\?\!]+'
    sentences = re.findall(pattern, text)

    return sentences

text = "Here we go again. I was supposed to add this text later.\
Well, it's 10.p.m. here, and I'm actually having fun making this course. :o\
I hope you are getting along fine with this presentation, I really did try.\
And one last sentence, just so you can test you tokenizers better."
text2= "Sos puto?Yo= creo. que si"
print("Tokenized sentences:")
print(tokenize_sentence(text))

print("Tokenized words:")
print(tokenize_words(text))





Tokenized sentences:
['Here we go again', ' I was supposed to add this text later', "Well, it's 10", 'p', 'm', " here, and I'm actually having fun making this course", ' :oI hope you are getting along fine with this presentation, I really did try', 'And one last sentence, just so you can test you tokenizers better']
Tokenized words:
['Here', 'we', 'go', 'again', 'I', 'was', 'supposed', 'to', 'add', 'this', 'text', 'later', 'Well', 'it', 's', '10', 'p', 'm', 'here', 'and', 'I', 'm', 'actually', 'having', 'fun', 'making', 'this', 'course', 'oI', 'hope', 'you', 'are', 'getting', 'along', 'fine', 'with', 'this', 'presentation', 'I', 'really', 'did', 'try', 'And', 'one', 'last', 'sentence', 'just', 'so', 'you', 'can', 'test', 'you', 'tokenizers', 'better']


 The tokenizer is not perfect, but I think it works fine. I cannot get to separate:oI properly.
 
 As you can see, I also have problems with the p.m if I am only allowed to use regex. Otherwise, I would go with an approach similar to my colleague Cibrán.

## Exercise 2. Get tags from Trump speech using NLTK

You should use the ``trump.txt`` file, read it and find the tags for each word. Use NLTK for it.

We have to download a couple of things for it to work.

In [2]:
import nltk 
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\jackt\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [3]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\jackt\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

We read the file and use pos_tag.

In [2]:
from nltk.tokenize import word_tokenize
from nltk import pos_tag

file = open("./datasets/trump.txt", "r",encoding="utf-8") 
trump = file.read()
words = word_tokenize(trump)
tags = pos_tag(words)


And we read everything nicely in a DataFrame:

In [3]:
import pandas as pd

df = pd.DataFrame( {"Words": [item[0] for item in tags], "Tags": [item[1] for item in tags]})
df.head(20)

Words Tags
0       Thank  NNP
1         you  PRP
2        very   RB
3        much   RB
4           .    .
5         Mr.  NNP
6     Speaker  NNP
7           ,    ,
8         Mr.  NNP
9        Vice  NNP
10  President  NNP
11          ,    ,
12    Members  NNP
13         of   IN
14   Congress  NNP
15          ,    ,
16        the   DT
17      First  NNP
18       Lady  NNP
19         of   IN

If we want to find the tag for a given word we can use the following function. We will try with 'Thank', which can be a verb or a noun:

In [4]:
def tag_word(word):
    return print(word,"can be tagged as",set(df["Tags"][df["Words"] == word])) 
    #We use set() to return unique tags
    

In [5]:
tag_word("Thank")

Thank can be tagged as {'VB', 'NNP'}


## Exercise 3. Get the nouns in the last 10 sentences from Trump's speech and find the nouns divided by sentencens. Use SpaCy.

Please use Python list features to get the last 10 sentences and display nouns from it.

In [37]:
import spacy

file = open("./datasets/trump.txt", "r",encoding='utf-8') 
trump = file.read() 

nlp = spacy.load("en_core_web_sm")
doc = nlp(trump)


n_sentences = 0 
for span in doc.sents: #We have to know the number of sentences.
       n_sentences += 1

n_aux = 0

for span in doc.sents: # I think these lines look horrible, but I didn't find anything better on the Internet. 
    n_aux += 1
    if n_aux >(n_sentences-10):
        print("Sentence",n_aux,":",span)
        nouns_sentence=[]
        for i in range(span.start, span.end):
         token = doc[i]
         if token.pos_ == 'NOUN':
          nouns_sentence.append(token)
        print("Nouns in sentence",n_aux,":", nouns_sentence)
        
   




Sentence 288 : When we fulfill this vision, when we celebrate our 250 years of glorious freedom, we will look back on tonight as when this new chapter of American greatness began.
Nouns in sentence 288 : [vision, years, freedom, tonight, chapter, greatness]
Sentence 289 : The time for small thinking is over.
Nouns in sentence 289 : [time, thinking]
Sentence 290 : The time for trivial fights is behind us.
Nouns in sentence 290 : [time, fights]
Sentence 291 : We just need the courage to share the dreams that fill our hearts, the bravery to express the hopes that stir our souls, and the confidence to turn those hopes and those dreams into action.


Nouns in sentence 291 : [courage, dreams, hearts, bravery, hopes, souls, confidence, hopes, dreams, action]
Sentence 292 : From now on, America will be empowered by our aspirations, not burdened by our fears; inspired by the future, not bound by failures of the past; and guided by our vision, not blinded by our doubts.


Nouns in sentence 292 :

I understand that God and United States, for example, do not count as nouns (https://spacy.io/usage/linguistic-features#pos-tagging)

## Exercise 4. Build your own Bag Of Words implementation using tokenizer created before 

You need to implement following methods:

- ``fit_transform`` - gets a list of strings and returns matrix with it's BoW representation
- ``get_features_names`` - returns list of words corresponding to columns in BoW

In [126]:
import numpy as np
import spacy

class BagOfWords:
    """Basic BoW implementation."""
    
    __nlp = spacy.load("en_core_web_sm")
    __bow_list = []
    
    # your code goes maybe also here    
    
    def fit_transform(self, corpus: list):
        
        #We create the dictionary and save the frequency:
        dictionary = []
        frequency = []
        words_sentence = []
        for sentence in corpus:
         words = tokenize_words(sentence)
         words_sentence.append(words)
         for word in words:
            if word not in dictionary:
                dictionary.append(word)
                frequency.append(0)
            else:
                frequency[dictionary.index(word)] += 1
                
         #We sort the dictionary according to the frequency:
        
        frequency_arg_sort = np.argsort(frequency) #sorted from less frequent to most frequent
        dictionary_sort = []
        for i in range(len(dictionary)):
            dictionary_sort.append(dictionary[frequency_arg_sort[-1-i]])
            
        # We check how many times the words in our dictionary appear in each sentence:
        
        bow_list=[]
        
        for i in range(len(words_sentence)):
            bow_list.append([0]*len(dictionary_sort))
            for j in range(len(words_sentence[i])):
                for k in range(len(dictionary_sort)):
                    if dictionary_sort[k] == words_sentence[i][j]:
                        bow_list[i][k] += 1
        
        self.dictionary_sort = dictionary_sort
        
        return np.array([bow_list])
    
    def get_feature_names(self) -> list:
        
        return self.dictionary_sort        
        
corpus = [
    'Bag Of Words is based on counting',
     'words occurences throughout multiple documents.',
     'This is the third document.',
     'As you can see most of the words occur only once.',
     'This gives us a pretty sparse matrix, see below. Really, see below']    

In [127]:
BagOfWords = BagOfWords()

bow= BagOfWords.fit_transform(corpus)
dictionary = BagOfWords.get_feature_names()


We can check that it works:

In [128]:
print(bow)
print(dictionary)

[[[0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
  [0 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0]
  [2 0 0 1 2 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0]]]
['see', 'words', 'the', 'This', 'below', 'is', 'based', 'on', 'counting', 'third', 'occurences', 'throughout', 'multiple', 'documents', 'Words', 'Of', 'Really', 'As', 'document', 'you', 'can', 'most', 'of', 'occur', 'only', 'once', 'gives', 'us', 'a', 'pretty', 'sparse', 'matrix', 'Bag']


## Exercise 5. Build a 5-gram model and clean up the results.

There are three tasks to do:
1. Use 5-gram model instead of 3.
2. Change to capital letter each first letter of a sentence.
3. Remove the whitespace between the last word in a sentence and . ! or ?.

Hint: for 2. and 3. implement a function called ``clean_generated()`` that takes the generated text and fix both issues at once. It could be easier to fix the text after it's generated rather then doing some changes in the while loop.

In [ ]:
from nltk.book import *

wall_street = text7.tokens

import re

tokens = wall_street

def cleanup():
    compiled_pattern = re.compile("^[a-zA-Z0-9.!?]")
    clean = list(filter(compiled_pattern.match,tokens))
    return clean
tokens = cleanup()

def build_ngrams():
    ngrams = []
    for i in range(len(tokens)-N+1):
        ngrams.append(tokens[i:i+N])
    return ngrams

def ngram_freqs(ngrams):
    counts = {}

    for ngram in ngrams:
        token_seq  = SEP.join(ngram[:-1])
        last_token = ngram[-1]

        if token_seq not in counts:
            counts[token_seq] = {}

        if last_token not in counts[token_seq]:
            counts[token_seq][last_token] = 0

        counts[token_seq][last_token] += 1;

    return counts

def next_word(text, N, counts):

    token_seq = SEP.join(text.split()[-(N-1):]);
    choices = counts[token_seq].items();

    total = sum(weight for choice, weight in choices)
    r = random.uniform(0, total)
    upto = 0
    for choice, weight in choices:
        upto += weight;
        if upto > r: return choice
    assert False # should not reach here

In [ ]:
def clean_generated():
    # put your code here
    pass

N=3 # fix it for other value of N

SEP=" "

sentence_count=5

ngrams = build_ngrams()
start_seq="We have"

counts = ngram_freqs(ngrams)

if start_seq is None: start_seq = random.choice(list(counts.keys()))
generated = start_seq.lower();

sentences = 0
while sentences < sentence_count:
    generated += SEP + next_word(generated, N, counts)
    sentences += 1 if generated.endswith(('.','!', '?')) else 0

# put your code here:

print(generated)